# Generated by Django 2.2.13 on 2020-07-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this article', to='catalog.Genre'),
        ),
    ]
